---
- hosts: pi
  become: true
  gather_facts: false

  vars_files:
    - config.yml

  pre_tasks:
    - name: Ensure git is installed.
      package: name=git state=present

  tasks:
    - include_tasks: tasks/uvc-gadget.yml
    - include_tasks: tasks/boot-config.yml
    - include_tasks: tasks/piwebcam.yml
    - include_tasks: tasks/install-arducam-drivers.yml
      when: arducam == true
